runtime: java11
instance_class: F2

#runtime_config:
#  jdk: openjdk11

#entrypoint: java -noverify -jar audiobeat-api-0.0.1-SNAPSHOT.jar
#entrypoint: java -Xmx64m -jar audiobeat-api/target/audiobeat-api-0.0.1-SNAPSHOT.jar

#
#handlers:
#  - url: /.*
#    script: this field is required, but ignored

# [END gae_flex_quickstart_yaml]
