CREATE TABLE IF NOT EXISTS CTMR
(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    CTMR_NM_FTS  VARCHAR(255) NOT NULL,
    CTMR_NM_COMP VARCHAR(255) NOT NULL,
    CTMR_CNPJ VARCHAR(18) NOT NULL,
    CTMR_ID_SECOM INTEGER NOT NULL,
    CTMR_TP_RDIO VARCHAR(50),
    CTMR_MNP VARCHAR(18) NOT NULL,
    CTMR_TP_SRVC VARCHAR(18) NOT NULL,
    CTMR_GNR VARCHAR(255) NOT NULL,

    UPDATE_AT timestamp NOT NULL,
    CREATE_AT timestamp NOT NULL

    );




